### PR TITLE
Select the first of the supported locales

### PR DESCRIPTION
**Pull request by OrKoN**
If the detected locale is undefined

### CODE REVIEW

**Comment by Dani723** [comment]
This would result in overwriting the Accept-Language with every request when there is a invalid persisted locale. But in this case we want so send the Accept-Language Header of the browser.
I think the overwriting should only kick in, when there is a persisted locale set AND it is supported locales.

**Comment by OrKoN** [comment]
@Dani723 Something like this?

**Comment by Dani723** [comment]
@OrKoN But that also overwrites the locale if the persisted one is not in supported locales?

**Comment by OrKoN** [comment]
@Dani723 It sets the locale if there is some locale in pl10Info and it's not supported.

**Comment by OrKoN** [comment]
@Dani723 I need locale to be `en` or `de` (not the undefined) on the page start up during the app initialization. I persist the locale myself into the location storage:

```
localeSet.set('locale', detectLocale());
localeSet.save();
```

But I don't check if it's supported

**Comment by OrKoN** [comment]
@Dani723 let's discuss this when you are here

**Comment by Dani723** [comment]
But your solution would also not help if there is no persisted locale at all.
The locale property should only return a value, when it is persisted and supported. Only then(!) the Accept-Language Header should be overwritten. In every other case, the default Accept-Language Header is sent by the Browser.

**Comment by OrKoN** [comment]
I don't need the locale for the accept-language header. I need it for the local data which already has all translations. Without knowing the locale on startup, the app initialization fails.

**Comment by OrKoN** [comment]
@Dani723 Is it possible to know the browser's locale from the request to get the supported locales?

**Comment by Dani723** [comment]
@OrKoN K, I understand.
The problem is, that we can't determine the users locale reliable, so the default Accept-Language Header should always be sent by the browser itself and not fallback to the first supported language.

But how about this solution:

There are 2 properties:
locale -> Always has a valid value. 1) persisted 2) fallback to first supported
browserLocale -> Only has a valid value when the persisted locale matches the supported locales. Otherwise undefined.

**Comment by OrKoN** [comment]
@Dani723 we could ask server to tell us what is the Accept-Language header set by the browser is ;-)

**Comment by OrKoN** [comment]
@Dani723 ```add_header  X-Accept-Language  $http_accept_language;```

**Pull request closed without merging**
